### ISSUE TITLE
Error on start server 

### ISSUE THREAD

**Issue by sawmodz** [MIdCoard/Pathfinder-ASM#2]
hi ^^, 
![Annotation 2020-11-01 203851](https://user-images.githubusercontent.com/41762589/97812568-51e1a280-1c82-11eb-866c-a217caaddc80.png)
i use paper 1.10.2

**Comment by MidCoard** [comment]
Did you run with the latest version?

**Comment by sawmodz** [comment]
Hi I'm shooting with the latest version but finally I've redone everything myself and it all works.

**Comment by MidCoard** [comment]
Fine. Thank you, I will fix it soon.

**Comment by MidCoard** [comment]
Oh. Sadly, I did not put my latest version on the tag. It is a mistake....
It is just a copy of 2.0 ....
But in fact, version 3.0 is already ok.

For the issue, I used the paper 1.10.2 but did not encounter the problem you meet.
And I think it may be caused by the JAVA enviroment. To better fix this problem, I have changed some of the codes so that it may not be occured again. However, I didnot know whether it will be ok for you so that maybe I would like to trouble you to test it. I'd appreciate it if you could help me !

**Comment by sawmodz** [comment]
no problem i start your plugin on my server

**Comment by sawmodz** [comment]
can you put your jar in release?

**Comment by MidCoard** [comment]
I put it now!

**Comment by MidCoard** [comment]
it is so complex that .... I want to be access to NMS Navigation. It is hard and my system did not perform well. Many parts of it are in a mess... And wiki is not updated....

**Comment by sawmodz** [comment]
at worst it doesn't matter I managed to do myself what I wanted you don't have to update it ^^

**Comment by MidCoard** [comment]
is it ok on your server ?

**Comment by sawmodz** [comment]
yes

**Comment by MidCoard** [comment]
Thanks.
